export const hostGoals = [

    'Send a good morning message 🌅',
    'Share a fun fact of the day 🤓',
    'Post a daily question (e.g., "Whats your comfort food?")',
    'React to someones message with emojis ❤️',
    'Welcome any new members with a warm message 🙌',
    'Start a “One Word Check-In” thread (“Today I feel ___”)',
    'Post a random meme or GIF 😂',
    'Drop a "this or that" choice (e.g., cats vs dogs 🐱🐶)',
    'Play a word association game in chat 🧠',
    'Ask a “Would You Rather” question 😬',
    'Tag a member and ask how their day is going 😊',
    'Share a music recommendation 🎵',
    'Post a challenge (e.g., “Send your current view 📸”)',
    'Celebrate someone’s small win 🥳',
    'Ask: "What’s something that made you smile today?"',
    'Share a quote or affirmation of the day 💬',
    'Post a “rate this...” image or topic 🔥',
    'Send a random “vibe check” 🌀',
    'Poll the group on a silly topic 🗳️',
    'Drop a riddle or puzzle to solve 🤔',
    'Encourage others to share their goals for the day 🎯',
    'Share your own mini goal or to-do list 📝',
    'Give someone a surprise compliment 🎁',
    'Ask for movie/show recommendations 🎬',
    'Start a “Picture of the Day” thread 🖼️',
    'Ask for one word to describe today so far ⌛',
    'React to every unread message 🧡',
    'Create a quick emoji-only conversation 🗨️',
    'Challenge the group to 5 push-ups or a stretch 💪',
    'Ask: “What’s for lunch/dinner?” 🍜',
    'Drop a funny tweet or TikTok link 📲',
    'Start a “Guess the Soundtrack” game 🎧',
    'Ask: “What’s your vibe today—chaotic or chill?”',
    'Start a “Fill in the Blank” game (“I never ___ but today I might...”)',
    'Post a screenshot of your home screen or playlist 📱',
    'Ask: “What’s your secret talent?” 🕵️‍♂️',
    'Do a shoutout for someone active yesterday 🎉',
    'Ask everyone to share a selfie or pet pic 📷🐶',
    'Post a daily horoscope (real or made-up 😂)',
    'Send a short voice message to greet the group 🎤',
    'Ask: “What’s something weird you saw today?” 👀',
    'Post a “Rate Your Day” scale from 1–10 🔢',
    'Ask for unpopular opinions 🤐',
    'Challenge everyone to take a break/stretch 🚶',
    'Post a single emoji and see who gets the meaning 🧩',
    'Start a 3-word story game 📝',
    'Share your current screen time or digital detox tip 📵',
    'Remind everyone to drink water 💧',
    'Ask: “What’s your biggest craving today?” 🍫',
    'Check if anyone needs support or a rant space 💬',
    'Post a 5-second voice note singing something 🎶',
    'Make up a fun “national day” (e.g., National Nap Day 😴)',
    'Start a weekly theme (e.g. “Gratitude Week”) 🙏',
    'Host a mini game (e.g. Trivia Tuesday, Meme Battle) 🎮',
    'Do a “Weekly Wins” roundup 🏆',
    'Introduce a “Spotlight Member of the Week” 🌟',
    'Launch a “Photo Dump Friday” thread 📸',
    'Ask the group to vote on next week’s theme 🗳️',
    'Invite members to share playlists or mood music 🎧',
    'Ask: “What’s one goal for the week?”',
    'Run a “Pet of the Week” contest 🐾',
    'Share your personal highlight of the week 🌈',
    'Do a “Vibe Check” survey (1–10) 📊',
    'Host a live Q&A or casual hangout 💬',
    'Post an inspirational story or user spotlight ✨',
    'Post a weekly reflection prompt (“What did you learn this week?”)',
    'Set a fun weekly challenge (e.g., 10k steps, no sugar, daily selfie) 💪',
    'Ask everyone to drop their weekend plans 🏖️',
    'Organize a voice chat or video call 📞',
    'Start a debate thread (“Pineapple on pizza: yes or no?”) 🍕',
    'Make a weekly “Shoutout Board” for active members 📣',
    'Post weekly poll results or fun stats 📊',
    'Assign a “Weekly Vibe Leader” (temporary co-host) 👑',
    'Drop a curated content bundle (links, memes, news) 📚',
    'Ask everyone to vote on their favorite message of the week 🏅',
    'Create a group collage or story recap with submissions 📷',
    'Introduce a “Question of the Week” 🧐',
    'Ask: “Who made your week better?” and tag them',
    'Celebrate group milestones (e.g., 1000 messages sent!) 🎉',
    'Create a group Spotify playlist from everyone’s faves 🎶',
    'Do a “Throwback Post” thread with old messages 📜',
    'Invite feedback: “How’s the group vibe lately?”',
    'Post a “What’s something new you tried this week?” prompt',
    'Organize a story chain (each member adds a sentence) 📖',
    'Celebrate birthdays or anniversaries 🎂',
    'Remind everyone of the community guidelines in a fun way 📌',
    'Create a “Joke of the Week” thread 😂',
    'Ask: “What’s one thing you’re grateful for this week?”',
    'Schedule a casual live hangout or audio drop-in 🕒',
    'Share your top meme of the week 🖼️',
    'Introduce new members formally in a group intro post 🙋',
    'Pick a random member to set next week’s theme 🎨',
    'Host a “Monthly Recap” with highlights and stats 📅',
    'Run a themed month (e.g. “Mental Health Month”) 🧠',
    'Create a “Monthly Challenge” (e.g., read 2 books, try a new hobby) 📚',
    'Invite members to share their favorite moments from the month 🌟',
    'Post a “Monthly Goals” thread for everyone to share 🎯',
    'Celebrate member anniversaries or milestones 🎉',
    'Ask: “What’s one thing you learned this month?” 📖',
    'Share a group photo or collage of the month’s best moments 📸',
    'Run a poll for next month’s theme or activities 🗳️',
    'Create a “Monthly Playlist” with everyone’s top tracks 🎶',
    'Host a live Q&A session with a special guest or expert 👥',
    'Post a “Best Meme of the Month” contest 🏆',
    'Encourage members to share their personal wins or achievements 🏅',
    'Start a book club or movie night for the month 📚🎬',
    'Ask: “What’s one thing you want to improve next month?” 🔄',
    'Share your favorite resource or tool from the past month 🔧',
    'Create a “Monthly Reflection” thread for deeper discussions 💭',
    'Invite members to suggest topics for next month’s chats 📝',
    'Celebrate the most active member of the month with a shoutout 👏',
    'Post a fun fact about the group or community history 📜',
    
]