export const allInterests = [
    'Biking',
    'Art',
    'Drawing',
    'Music',
    'Hiking',
    'Gaming',
    'Cooking',
    'Dancing',
    'Coding',
    'Reading',
    'Photography',
    'Writing',
    'Traveling',
    'Fashion',
    'Technology',
    'Fitness',
    'Yoga',
    'Volunteering',
    'Sports',
    'Gardening',
    'Fishing',
    'Running',
    'Swimming',
    'Cycling',
    'Knitting',
    'Pottery',
    'Jewelry Making',
    'Sculpting',
    'Astronomy',
    'Chess',
    'Learning Languages',
    'Podcasting',
    'Blogging',
    'Public Speaking',
    'Entrepreneurship',
    'Investing',
    'Reading Science Fiction',
    'Collecting',
    'Writing Poetry',
    'Cooking International Cuisine',
    'Wine Tasting',
    'Brewing',
    'Sewing',
    'Interior Design',
    'Woodworking',
    'Home Brewing',
    'Surfing',
    'Skiing',
    'Snowboarding',
    'Rock Climbing',
    'Scuba Diving',
    'Caving',
    'Motorsports',
    'Watching Documentaries',
    'Birdwatching',
    'Geocaching',
    'Board Games',
    'Video Game Development',
    'Digital Art',
    '3D Modeling',
    'Virtual Reality',
    'Augmented Reality',
    'Puzzles',
    'Mental Health Advocacy',
    'History',
    'Philosophy',
    'Politics',
    'Debating',
    'Public Policy',
    'Cultural Studies',
    'Fitness Tracking',
    'Minimalism',
    'DIY Projects',
    'Upcycling',
    'Luxury Travel',
    'Baking',
    'Cake Decorating',
    'Mixology',
    'Camping',
    'Clothing Design',
    'Model Making',
    'Magic',
    'Origami',
    'Language Exchange',
    'Community Service',
    'Stand-up Comedy',
    'Improv Theater',
    'Voice Acting',
    'Animal Rescue',
    'Pet Training',
    'Recycling',
    'Social Media Marketing',
    'Search Engine Optimization',
    'Vlogging',
    '3D Printing',
    'Web Design',
    'App Development',
    'Blockchain Technology',
    'Cryptocurrency',
    'Artificial Intelligence',
    'Machine Learning',
    'Deep Learning',
    'Virtual Worlds',
    'Graphic Design',
    'UX/UI Design',
    'Event Planning',
    'Culinary Arts',
    'Mixing Music',
    'DJing',
    'Salsa Dancing',
    'Hip Hop Dancing',
    'Classical Music',
    'Guitar Playing',
    'Piano Playing',
    'Drumming',
    'Violin Playing',
    'Composing Music',
    'LARPing',
    'Cosplaying',
    'Martial Arts',
    'Self-Defense Training',
    'Journaling',
    'Mindfulness Meditation',
    'Breathing Exercises',
    'Sailing',
    'Kayaking',
    'Stand-up Paddleboarding',
    'Fitness Bootcamps',
    'Parkour',
    'Triathlon',
    'Tennis',
    'Golf',
    'Soccer',
    'Baseball',
    'Basketball',
    'Football',
    'Volleyball',
    'Table Tennis',
    'Badminton',
    'Archery',
    'Bowling',
    'Cricket',
    'Rugby',
    'Fencing',
    'Lacrosse',
    'Horseback Riding',
    'Fly Fishing',
    'Dog Training',
    'Paragliding',
    'Hang Gliding',
    'Base Jumping',
    'Hot Air Ballooning',
    'Motorcycling',
    'Shooting Sports',
    'Rock Band',
    'Choreography',
    'Theater',
    'Poetry Slam',
    'Film Making',
    'Video Editing',
    'Crafting',
    'DIY Home Improvements',
    'Product Design',
    'Fashion Design',
    'Personal Finance',
    'Home Automation',
    'Genealogy',
    'Botany',
    'Beekeeping',
    'Coin Collecting',
    'Antique Collecting',
    'Stargazing',
    'Urban Exploration',
    'Cryptozoology',
    'Magic Tricks',
    'Conspiracy Theories',
    'Nostalgia',
    'Reality TV Shows',
    'Political Activism',
    'Humanitarian Work',
    'Philanthropy',
    'Animal Behavior',
    'Space Exploration',
    'Futurism',
    'Neuroscience',
    'Sociology',
    'Psychology',
    'Economics',
    'Game Theory',
    'Cognitive Science',
    'Genetics',
    'Marine Biology',
    'Microbiology',
    'Botanical Gardens',
    'Aquarium Keeping',
    'Herpetology',
    'Zoology',
    'Environmentalism',
    'Sustainability',
    'Climate Change Awareness',
    'Solar Energy',
    'Wind Energy',
    'Sustainable Fashion',
    'Upcycled Furniture',
    'Zero Waste Lifestyle',
    'Green Building',
    'Electric Cars',
    'Sustainable Food',
    'Sustainable Architecture',
    'Geology',
    'Meteorology',
    'Volcano Watching',
    'Meteor Shower Viewing',
    'Ice Climbing',
    'Eco-Tourism',
    'Waste Reduction',
    'Composting',
    'Urban Farming',
    'Food Forests',
    'Permaculture',
    'Water Conservation',
    'Urban Gardening',
    'Foraging',
    'Wildlife Conservation',
    'Pet Photography',
    'Self-Publishing',
    'Storytelling',
    'Camping Cooking',
    'Podcast Production',
    'Public Art Installations',
    'Street Art',
    'Tattoo Art',
    'Graphic Novels',
    'Comic Book Collecting',
    'Fan Fiction Writing',
    'Costume Design',
    'Circus Arts',
    'Parkour Training',
    'Extreme Sports',
    'Bouldering',
    'Astronautics',
    'Space Tourism',
    'Exoplanet Hunting',
    'Robot Building',
    'Biohacking',
    'Quantum Computing',
    'Personal Development',
    'Digital Nomad Lifestyle',
    'Minimalist Travel',
    'Digital Detox',
    'Mindful Eating',
    'Permaculture Design',
    'Candle Making',
    'Soap Making',
    'Homeopathy',
    'Herbal Medicine',
    'Aquaponics',
    'Vintage Car Restoration',
    'Classic Motorcycles',
    'Slot Car Racing',
    'Boardgame Design',
    'Tabletop RPGs',
    'Online Learning',
    'Digital Marketing',
    'Crowdsourcing',
    'Crowdfunding',
    'Collaborative Economy',
    'Smart Home Technologies',
    'VR Gaming',
    'Indie Game Development',
    'Live Streaming',
    'Artificial Intelligence Ethics',
    'Smart Wearables',
    'Fitness Gadgets',
    'Mind Mapping',
    'Memory Training',
    'Mind Games',
    'Public Transportation',
    'Blockchain Gaming',
    'Voice User Interface Design',
    'Automated Systems',
    'Sustainable Business',
    'CrossFit',
    'Powerlifting',
    'Strength Training',
    'Circuit Training',
    'Kettlebell Workouts',
    'Bodyweight Exercises',
    'Dance Fitness',
    'Zumba',
    'HIIT Workouts',
    'Pilates',
    'Barre',
    'Martial Arts Training',
    'CrossFit Games',
    'Park Fitness',
    'Spinning',
    'Mountain Biking',
    'Triathlons',
    'Obstacle Course Racing',
    'Trail Running',
    'Endurance Events',
    'Cross-country Skiing',
    'Ski Mountaineering',
    'Marathons',
    'Walking Tours',
    'Mushroom Foraging',
    'Cooking with Kids',
    'Meal Prepping',
    'Bread Making',
    'Gourmet Cooking',
    'Cheese Making',
    'Wildlife Photography',
    'Underwater Photography',
    'Sports Photography',
    'Street Photography',
    'Vintage Photography',
    'Travel Photography',
    'Fashion Photography',
    'Fine Art Photography',
    'Nature Photography',
    'Conceptual Photography',
    'Aerial Photography',
    'Drone Photography',
    'Film Photography',
    'Experimental Photography',
    'Self-Portrait Photography',
    'Architectural Photography',
    'Food Photography',
    'Portrait Photography',
    'Music Production',
    'Audio Engineering',
    'Songwriting',
    'Video Game Music',
    'Sound Design',
    'Film Scoring',
    'Theater Production',
    'Dance Choreography',
    'Music Composition',
    'Event Photography',
    'Interactive Media',
    'Geography',
    'Urban Studies',
    'Cultural Heritage',
    'Traditional Craftsmanship',
    'Historical Reenactment',
    'Astrology',
    'Self-Improvement',
    'Brain Teasers',
    'Personal Branding',
    'Time Management',
    'Life Coaching',
    'Productivity Systems',
    'Critical Thinking',
    'Positive Psychology',
    'Assertiveness Training',
    'Creative Writing',
    'Memoir Writing',
    'Historical Fiction Writing',
    'Thriller Writing',
    'Fantasy Fiction Writing',
    'Screenwriting',
    'Journal Writing',
    'Fictional World Building',
    'Nonfiction Writing',
    'Book Clubbing',
    'Foreign Language Learning',
    'Polyglot Community',
    'Cultural Exchanges',
    'Mentalism',
    'Escape Rooms',
    'Treasure Hunts',
    'DIY Electronics',
    'IoT Projects',
    'Hardware Hacking',
    'Smart Device Integration',
    'Environmental Activism',
    'Green Living',
    'Public Transportation Advocacy',
    'Philanthropic Ventures',
    'Civic Engagement',
    'Political Campaigns',
    'Urban Mobility',
    'Election Integrity',
    'Peacebuilding',
    'International Relations',
    'Human Rights Advocacy',
    'Refugee Support',
    'Anti-Corruption Initiatives',
    'Indigenous Rights',
    'Disability Advocacy',
    'Gender Equality',
    'Racial Justice',
    'Legal Reform',
    'Animal Rights',
    'Healthcare Reform',
    'Youth Empowerment',
    'Reproductive Rights',
    'Affordable Housing',
    'Hate Crime Prevention',
    'Gun Control Advocacy',
    'Climate Change Action',
    'Food Security',
    'Global Development',
    'Water Accessibility',
    'Peace Corps',
    'Community Organizing',
    'Disaster Relief',
    'International Aid',
    'Emergency Preparedness',
    'Urban Resilience',
    'Crisis Response',
    'Refugee Integration',
    'Legal Aid',
    'Ex-Offender Rehabilitation',
    'Civil Liberties',
    'Disability Rights',
    'LGBTQIA+ Rights',
    'Health Advocacy',
    'Anti-Poverty Initiatives',
    'Mental Health Support',
    'Addiction Recovery',
    'Senior Citizen Care',
    'Social Work',
    'Crisis Intervention',
    'HIV/AIDS Prevention',
    'Suicide Prevention',
    'Disaster Recovery',
    'Environmental Education',
    'Ocean Conservation',
    'Community Gardens',
    'Sustainable Tourism',
    'Rural Development',
    'Healthcare Access',
    'Gender-Based Violence Prevention',
    'Human Trafficking Awareness',
    'Inclusive Education',
    'Natural Disaster Relief',
    'Recycling Programs',
    'Waste Management',
    'Zero-Waste Communities',
    'Water Purification'
];
