/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/matchmakingReport` | `/matchmakingReport`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/verificationReport` | `/verificationReport`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/verifyUsers` | `/verifyUsers`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/matchmakingReport` | `/matchmakingReport`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/verificationReport` | `/verificationReport`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/verifyUsers` | `/verifyUsers`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/matchmakingReport${`?${string}` | `#${string}` | ''}` | `/matchmakingReport${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/verificationReport${`?${string}` | `#${string}` | ''}` | `/verificationReport${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/verifyUsers${`?${string}` | `#${string}` | ''}` | `/verifyUsers${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/matchmakingReport` | `/matchmakingReport`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/verificationReport` | `/verificationReport`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/verifyUsers` | `/verifyUsers`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
